name: AOT Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - name: install pre-req
      run: sudo apt-get install clang zlib1g-dev libkrb5-dev libssl-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: git fetch --prune --unshallow --tags
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-linux64
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.5.21302.13
    - name: Install GitVersion
      run: dotnet tool install --global --version 5.6.7 GitVersion.Tool
    - name: Restore dependencies
      run: dotnet restore
    - name: AOT build
      run: dotnet publish -r ubuntu-x64 -c Release
      working-directory: ./backend/mana.backend.ishtar.light
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ubuntu-aot-build
        path: ./backend/mana.backend.ishtar.light/bin/Release/net6.0/ubuntu-x64/native
        if-no-files-found: error
