name: coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: windows-latest

    steps:
    - name: Export Env
      run: $env:CODACY_PROJECT_TOKEN="${{ secrets.CODACY_API_KEY }}"
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: git fetch --prune --unshallow --tags
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.5.21302.13
    - name: Install DotCover
      run: dotnet tool install --global JetBrains.dotCover.GlobalTool --version 2021.2.0-eap03
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet dotcover test --no-build --dcReportType=DetailedXml
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@1.0.0
      with:
        project-token: ${{ secrets.CODACY_API_KEY }}
        coverage-reports: dotCover.Output.xml
