name: OSS

on:
  pull_request_target:
    branches: [master]
    types: [synchronize, opened, labeled, unlabeled]
  issues:
    types: [opened, labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  main:
    name: Governance
    runs-on: ubuntu-latest
    steps:
      - uses: DeFiCh/oss-governance-bot@v2
        with:
          github-token: ${{ secrets.CODE_MAID_PAT }}
